# ---------- Stage 1: Build ----------
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --production=false

COPY . .

# ---------- Stage 2: Production ----------
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .

ENV NODE_ENV=production
EXPOSE 5000

CMD ["node", "server.js"]